version: '2.1'

services:
  mai-db-node-ex01:
    build:
      context: mariadb
      dockerfile: Dockerfile
    container_name: mai-db-node
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: archdb
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - arch-network
    ports:
      - 3360:3306
    healthcheck:
      test: "/usr/bin/mysql --user=stud --password=stud --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 5
    volumes:
      - db-node-ex01-data:/var/lib/mysql

  auth_service:
    build:
      context: auth_service
      dockerfile: Dockerfile
    container_name: auth_servic
    environment:
      - DB_HOST=mai-db-node-ex01
      - DB_PORT=3306
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
    ports: 
      - 8082:8082
    networks:
      - arch-network
    depends_on:
      mai-db-node-ex01:
        condition: service_healthy
  service_service:
    build:
      context: service_service
      dockerfile: Dockerfile
    container_name: service_servic
    environment:
      - DB_HOST=mai-db-node-ex01
      - DB_PORT=3306
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
      - SERVICE_HOST=auth_service
    ports: 
      - 8083:8083
    networks:
      - arch-network
    depends_on:
      mai-db-node-ex01:
        condition: service_healthy
      auth_service:
        condition: service_started
  order_service:
    build:
      context: order_service
      dockerfile: Dockerfile
    container_name: order_servic
    environment:
      - DB_HOST=mai-db-node-ex01
      - DB_PORT=3306
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
      - SERVICE_HOST=auth_service
    ports: 
      - 8084:8084
    networks:
      - arch-network
    depends_on:
      mai-db-node-ex01:
        condition: service_healthy
      service_service:
        condition: service_started

volumes:
  db-node-ex01-data:

networks:
  arch-network:
    driver: "bridge"
    external: false